routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('notas');
});*/
/*

Route::get('/',['as'=>'notas.index','uses'=>'NotasController@index']);*/
/*
use GuzzleHttp\Client;
Route::get('/', function () {


    //return view('notas');
});

*/

//Route::get('/','NotasController@index');
/*
Route::get('/', function () {
    return view('facultades');
});*/
Route::get('/',['as'=>'facultades.index','uses'=>'FacultadesController@index']);
Route::post('/',['as'=>'facultades.show','uses'=>'FacultadesController@show']);

Route::resource('estudiantes', 'EstudianteController');
Route::resource('usuarios', 'UsuarioController');


/*
Route::get('estudiantes/create',['as'=>'estudiantes.create','uses'=>'EstudianteController@create']);
Route::post('estudiantes/store',['as'=>'estudiantes.store','uses'=>'EstudianteController@store']);
*/
/*
Route::get('estudiantes.create', 'EstudianteController@create');
Route::post('estudiantes.store', 'EstudianteController@store');*/

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Redirect;

class UsuarioController extends Controller
{
    //
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuarios=User::orderBy('username','asc')->paginate();
        return view ('usuarios.index',compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('usuarios.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user= User::create([
             'username'=>$request['username'],
             'email'=>$request['email'],
             'password'=>$request['password']
         ]);
        return redirect('usuarios')->with('message','store');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user=User::find($id);
        return view('usuarios.edit',['user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request)
    {   
        $user=User::find($id);
        $user->fill($request->all());
        $user->save();
        //
        return Redirect::to('/usuarios');
        //dd($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/usuarios/create.blade.php
@extends('app')
@section('content')
    <h1> Registrar Usuarios </h1>
    <br>
    <form class="" action="{{ route('usuarios.store') }}" method="POST">
        @csrf <!-- {{ csrf_field() }} -->
        @include('usuarios.form.formuser');
    </form>
@endsection

resources/views/usuarios/edit.blade.php
@extends('app')
@section('content')
    <h1> Editar Usuarios </h1>
    <br>
    <form class="" action="{{ route('usuarios.update',$user->id) }}" method="POST">
        {{method_field('PATCH')}}
        {{ csrf_field() }}
        @include('usuarios.form.formuser');
    </form>
@endsection

resources/views/usuarios/index.blade.php
@extends('app')
<?php
    $message=Session::get('message');
 ?>
 @if($message=='store')
 <div class="alert alert-success" role="alert">
     Los datos se han guardado con exito
</div>
 @endif
@section('content')
<h1> Listado de Usuarios</h1>
    <div class="row">
        <div class="col-md-12 text-right" style="margin:10px;" >
            <a href="{{ url('/usuarios/create') }}" class="btn btn-primary">New User</a>
        </div>
    </div>
    <div id="contendorflex">

        <table class="table table-bordered table-striped">
            <thead>
                <tr><th>#</th><th>Username</th><th>Email</th><th>Operaciones</th></tr>
            </thead>
            <tbody>
                <?php  $pos=0; ?>
                @foreach($usuarios as $user)
                <?php  $pos++; ?>
                    <tr>
                        <td>{{$pos}}</td>
                        <td>{{$user->username}}</td>
                        <td>{{$user->email}}</td>

                        <td><a href="{{ url('/usuarios/'.$user->id.'/edit') }}"><i class="fas fa-edit"></i></a></td>
                    </tr>
                @endforeach

            </tbody>

        </table>
        {!! $usuarios->render(); !!}
    </div>

@endsection